# Required
version: 2

# Image to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

# Configuration
python:
  install:
    - requirements: docs/requirements.txt
