# Required
version: 2

# Image to use
build:
  os: ubuntu-20.14
  tools:
    python: "3.8.12"

# Configuration
python:
  version: 3.8.12
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
